---
name: "C4GT Community Template"
description: "Create a new Ticket for C4GT Community"
title: "[C4GT Community]: "
labels:
  - "C4GT Community"

body:
  - type: textarea
    id: ticket-description
    validations:
      required: true
    attributes:
      label: "Ticket Contents"
      default: |
        ## Description
        [Provide a brief project description, outlining the need and measurable goals of the feature to be developed. 
        Kindly specify the number of users or scale of the product and feature, articulating its anticipated impact 
        and intended use. If this is a bounty ticket, also add the bounty amount. 
        For Design, Mentorship, & Advisory tickets, we recommend making a copy of this 
        [Google Form](https://docs.google.com/forms/d/18EPdoqBUFS6lRoQQbRKKjTvzA711nNTdmU8jinKTXWs/edit)
        and attaching a link to it. This way you can track applicants and assign the ticket appropriately.]

  - type: textarea
    id: ticket-goals
    validations:
      required: true
    attributes:
      label: "Goals"
      description: "List the goals of the feature."
      default: |
        ## Goals
        - [ ] [Goal 1]
        - [ ] [Goal 2]
        - [ ] [Goal 3]
        - [ ] [Goal 4]
        - [ ] [Goal 5]
        [Add any installation or setup steps here if relevant.]

  - type: textarea
    id: ticket-expected-outcome
    validations:
      required: true
    attributes:
      label: "Expected Outcome"
      description: "Describe in detail what the final product or result should look like and how it should behave."

  - type: textarea
    id: ticket-acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "List the acceptance criteria for this feature."

  - type: textarea
    id: ticket-implementation-details
    validations:
      required: true
    attributes:
      label: "Implementation Details"
      description: "List any technical details, technologies, or frameworks required."

  - type: textarea
    id: ticket-mockups
    attributes:
      label: "Mockups/Wireframes"
      description: "Include links to any visual aids, mockups, wireframes, or diagrams that illustrate the final product."

  - type: input
    id: ticket-product
    validations:
      required: true
    attributes:
      label: "Product Name"
      placeholder: "Enter Product Name"

  - type: dropdown
    id: ticket-organisation
    validations:
      required: true
    attributes:
      label: "Organisation Name"
      description: "Choose an organisation"
      multiple: false
      options:
        - C4GT
        - Dhiway
        - FIDE
        - SamagraX
        - ShikshaLokam
        - Tech4Dev
        - Tibil
        - ONDC
        - ONEST

  - type: input
    id: ticket-governance-domain
    attributes:
      label: "Domain"
      placeholder: "Enter Area of Governance"

  - type: dropdown
    id: ticket-technical-skills-required
    validations:
      required: true
    attributes:
      label: "Tech Skills Needed"
      description: "Select the tech stack for this ticket (use Ctrl/Command to select multiple)."
      multiple: true
      options:
        - .NET
        - Agile
        - Angular
        - Artificial Intelligence
        - ASP.NET
        - AWS
        - Babel
        - Bootstrap
        - C#
        - Chart.js
        - CI/CD
        - Computer Vision
        - CORS
        - cURL
        - Cypress
        - D3.js
        - Database
        - Debugging
        - Design
        - DevOps
        - Django
        - Docker
        - Electron
        - ESLint
        - Express.js
        - Feature
        - Flask
        - Go
        - GraphQL
        - HTML
        - Ionic
        - Jest
        - Java
        - JavaScript
        - Jenkins
        - JWT
        - Kubernetes
        - Laravel
        - Machine Learning
        - Maintenance
        - Markdown
        - Material-UI
        - Microservices
        - MongoDB
        - Mobile
        - Mockups
        - Mocha
        - Natural Language Processing
        - NestJS
        - Node.js
        - NUnit
        - OAuth
        - Performance Improvement
        - Prettier
        - Python
        - Question
        - React
        - React Native
        - Redux
        - RESTful APIs
        - Ruby
        - Ruby on Rails
        - Rust
        - Scala
        - Security
        - Selenium
        - SEO
        - Serverless
        - Solidity
        - Spring Boot
        - SQL
        - Swagger
        - Tailwind CSS
        - Test
        - Testing Library
        - Three.js
        - TypeScript
        - UI/UX/Design
        - Virtual Reality
        - Vue.js
        - WebSockets
        - Webpack
        - Other

  - type: textarea
    id: ticketorg-mentors
    validations:
      required: true
    attributes:
      label: "Organizational Mentor"
      description: "Tag or list relevant mentors for the ticket."

  - type: textarea
    id: ticketangel-mentors
    attributes:
      label: "Angel Mentor"
      description: "Tag or list relevant mentors for the ticket (if any)."

  - type: dropdown
    id: ticket-complexity
    validations:
      required: true
    attributes:
      label: "Complexity"
      description: "Choose a complexity describing this ticket."
      multiple: false
      options:
        - Low
        - Medium
        - High

  - type: dropdown
    id: ticket-category
    validations:
      required: true
    attributes:
      label: "Category"
      description: "Choose the categories that best describe this ticket."
      multiple: true
      options:
        - API
        - Analytics
        - Accessibility
        - Backend
        - Breaking Change
        - Beginner Friendly
        - Configuration
        - CI/CD
        - Database
        - Data Science
        - Deprecation
        - Documentation
        - Delpoyment
        - Frontend
        - Internationalization
        - Localization
        - Machine Learning
        - Maintenance
        - Mobile
        - Performance Improvement
        - Question
        - Refactoring
        - Research
        - Needs Reproduction
        - SEO
        - Security
        - Testing
        - Other
