name: "C4GT Open Community Template"
description: "Create a new Ticket for C4GT Open Community"
title: "[C4GT Community]: "
labels:
  - "C4GT Community"

body:
  - type: textarea
    id: ticket-description
    validations:
      required: true
description: "Create a new Ticket for C4GT Open Community"
title: "[C4GT Community]: "
labels:
  - "C4GT Community"

body:
  - type: textarea
    id: ticket-description
    validations:
      required: true
    attributes:
      label: Ticket Contents
      description: "Provide a detailed description of the ticket"
      placeholder: |
        ## Description
        [Provide a brief project description, outlining the need and measurable goals]

        **Key functionalities**:
        - Feature 1
        - Feature 2
        - Feature 3

        **Reference links**:
        - Link 1
        - Link 2
        - Link 3

        **Expected Timeline**: 
        **Bounty (if applicable)**: 

  - type: textarea
    id: ticket-goals
    validations:
      required: true
    attributes:
      label: Goals
      description: "List the goals of the feature"
      placeholder: |
        ## Goals
        - [ ] Goal 1
        - [ ] Goal 2
        - [ ] Goal 3
        - [ ] Goal 4
        - [ ] Goal 5

        [Setup Guide/Documentation links if any]

  - type: textarea
    id: ticket-expected-outcome-contributor
    validations:
      required: true
    attributes:
      label: Expected Outcome from Contributor
      description: "Describe in detail what the final product or result should look like and how it should behave"
      placeholder: |
        ## Expected Outcome
        Describe the expected deliverables and outcomes from the contributor:
        - Outcome 1
        - Outcome 2
        - Outcome 3

  - type: textarea
    id: ticket-expected-outcome-mentor
    validations:
      required: true
    attributes:
      label: Expected Outcome from Mentor
      description: "Describe in detail the expectations from the mentors"
      placeholder: |
        ## Mentor Expectations
        - Expectation 1
        - Expectation 2
        - Expectation 3

  - type: textarea
    id: ticket-acceptance-criteria
    validations:
      required: true
    attributes:
      label: Acceptance Criteria
      description: "List the acceptance criteria for this feature"
      placeholder: |
        ## Acceptance Criteria
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3

  - type: textarea
    id: ticket-implementation-details
    validations:
      required: true
    attributes:
      label: Implementation Details
      description: "List any technical details about the proposed implementation, including any specific technologies that will be used"
      placeholder: |
        ## Implementation Details
        - **Language**: 
        - **Architecture**: 
        - **Database**: 
        - **Deployment**: 
        - **Security**: 
        - **Design Paradigm**: 

  - type: textarea
    id: ticket-mockups
    attributes:
      label: Mockups/Wireframes
      description: "Include links to any visual aids, mockups, or diagrams"
      placeholder: |
        ## Mockups/Wireframes
        [Add links or descriptions of any visual aids]

  - type: input
    id: ticket-product
    attributes:
      label: Product Name
      placeholder: "Enter Product Name"
    validations:
      required: true

  - type: dropdown
    id: ticket-organisation
    attributes:
      label: Organisation Name
      description: "Enter Organisation Name"
      multiple: false
      options:
        - C4GT
        - Dhiway
        - FIDE
        - SamagraX
        - ShikshaLokam
        - Tech4Dev
        - Tibil
        - ONDC
        - ONEST
    validations:
      required: true

  - type: input
    id: ticket-governance-domain
    attributes:
      label: Domain
      placeholder: "Enter Area of Governance"
    validations:
      required: true

  - type: dropdown
    id: ticket-technical-skills-required
    attributes:
      label: Tech Skills Needed
      description: "Select the technologies needed for this ticket (use Ctrl or Command to select multiple)"
      multiple: true
      options:
        - .NET
        - Agile
        - Angular
        - Artificial Intelligence
        - ASP.NET
        - AWS
        - Babel
        - Bootstrap
        - C#
        - Chart.js
        - CI/CD
        - Computer Vision
        - CORS
        - cURL
        - Cypress
        - D3.js
        - Database
        - Debugging
        - Design
        - DevOps
        - Django
        - Docker
        - Electron
        - ESLint
        - Express.js
        - Feature
        - Flask
        - Go
        - GraphQL
        - HTML
        - Ionic
        - Jest
        - Java
        - JavaScript
        - Jenkins
        - JWT
        - Kubernetes
        - Laravel
        - Machine Learning
        - Maintenance
        - Markdown
        - Material-UI
        - Microservices
        - MongoDB
        - Mobile
        - Mockups
        - Mocha
        - Natural Language Processing
        - NestJS
        - Node.js
        - NUnit
        - OAuth
        - Performance Improvement
        - Prettier
        - Python
        - Question
        - React
        - React Native
        - Redux
        - RESTful APIs
        - Ruby
        - Ruby on Rails
        - Rust
        - Scala
        - Security
        - Selenium
        - SEO
        - Serverless
        - Solidity
        - Spring Boot
        - SQL
        - Swagger
        - Tailwind CSS
        - Test
        - Testing Library
        - Three.js
        - TypeScript
        - UI/UX/Design
        - Virtual Reality
        - Vue.js
        - WebSockets
        - Webpack
        - Other
    validations:
      required: true

  - type: dropdown
    id: ticket-mentorship
    attributes:
      label: Mentorship Status
      description: "Choose the mentorship status for this ticket"
      multiple: false
      options:
        - Mentor Required
        - Mentor Selected
        - Mentorship Completed
        - Mentor not required
    validations:
      required: true

  - type: textarea
    id: ticket-mentors
    attributes:
      label: Mentor(s)
      description: "Please tag relevant mentors for the ticket"
      placeholder: "Tag mentors using their GitHub handles (@username)"
    validations:
      required: true

  - type: dropdown
    id: ticket-complexity
    attributes:
      label: Complexity
      description: "Choose a complexity describing the complexity of your ticket"
      multiple: false
      options:
        - Foundational
        - Low
        - Medium
        - High
        - Advanced
    validations:
      required: true

  - type: dropdown
    id: ticket-project-type
    attributes:
      label: Contribution Type
      description: "Choose the labels that best describe this project"
      multiple: true
      options:
        - Code contribution
        - UI / UX design 
        - Advisory
        - Mentorship
        - Others
    validations:
      required: true

  - type: dropdown
    id: ticket-issue-type
    attributes:
      label: Issue Type
      description: "Choose the labels that best describe this ticket"
      multiple: true
      options:
        - Unpaid ticket
        - Paid ticket
        - Bounty ticket 
    validations:
      required: true

  - type: textarea
    id: ticket-monetary-incentive
    attributes:
      label: Monetary Incentive
      description: "Please mention the amount (in INR/USD) in case of a bounty / paid ticket. Please mention NA in case it is an unpaid ticket"
      placeholder: "Enter amount in INR/USD or NA"
    validations:
      required: true

      description: "Provide a detailed description of the ticket"
      placeholder: |
        ## Description
        [Provide a brief project description, outlining the need and measurable goals]

        **Key functionalities**:
        - Feature 1
        - Feature 2
        - Feature 3

        **Reference links**:
        - Link 1
        - Link 2
        - Link 3

        **Expected Timeline**: 
        **Bounty (if applicable)**: 

  - type: textarea
    id: ticket-goals
    validations:
      required: true
    attributes:
      label: Goals
      description: "List the goals of the feature"
      placeholder: |
        ## Goals
        - [ ] Goal 1
        - [ ] Goal 2
        - [ ] Goal 3
        - [ ] Goal 4
        - [ ] Goal 5

        [Setup Guide/Documentation links if any]

  - type: textarea
    id: ticket-expected-outcome-contributor
    validations:
      required: true
    attributes:
      label: Expected Outcome from Contributor
      description: "Describe in detail what the final product or result should look like and how it should behave"
      placeholder: |
        ## Expected Outcome
        Describe the expected deliverables and outcomes from the contributor:
        - Outcome 1
        - Outcome 2
        - Outcome 3

  - type: textarea
    id: ticket-expected-outcome-mentor
    validations:
      required: true
    attributes:
      label: Expected Outcome from Mentor
      description: "Describe in detail the expectations from the mentors"
      placeholder: |
        ## Mentor Expectations
        - Expectation 1
        - Expectation 2
        - Expectation 3

  - type: textarea
    id: ticket-acceptance-criteria
    validations:
      required: true
    attributes:
      label: Acceptance Criteria
      description: "List the acceptance criteria for this feature"
      placeholder: |
        ## Acceptance Criteria
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3

  - type: textarea
    id: ticket-implementation-details
    validations:
      required: true
    attributes:
      label: Implementation Details
      description: "List any technical details about the proposed implementation, including any specific technologies that will be used"
      placeholder: |
        ## Implementation Details
        - **Language**: 
        - **Architecture**: 
        - **Database**: 
        - **Deployment**: 
        - **Security**: 
        - **Design Paradigm**: 

  - type: textarea
    id: ticket-mockups
    attributes:
      label: Mockups/Wireframes
      description: "Include links to any visual aids, mockups, or diagrams"
      placeholder: |
        ## Mockups/Wireframes
        [Add links or descriptions of any visual aids]

  - type: input
    id: ticket-product
    attributes:
      label: Product Name
      placeholder: "Enter Product Name"
    validations:
      required: true

  - type: dropdown
    id: ticket-organisation
    attributes:
      label: Organisation Name
      description: "Enter Organisation Name"
      multiple: false
      options:
        - C4GT
        - Dhiway
        - FIDE
        - SamagraX
        - ShikshaLokam
        - Tech4Dev
        - Tibil
        - ONDC
        - ONEST
    validations:
      required: true

  - type: input
    id: ticket-governance-domain
    attributes:
      label: Domain
      placeholder: "Enter Area of Governance"
    validations:
      required: true

  - type: dropdown
    id: ticket-technical-skills-required
    attributes:
      label: Tech Skills Needed
      description: "Select the technologies needed for this ticket (use Ctrl or Command to select multiple)"
      multiple: true
      options:
        - .NET
        - Agile
        - Angular
        - Artificial Intelligence
        - ASP.NET
        - AWS
        - Babel
        - Bootstrap
        - C#
        - Chart.js
        - CI/CD
        - Computer Vision
        - CORS
        - cURL
        - Cypress
        - D3.js
        - Database
        - Debugging
        - Design
        - DevOps
        - Django
        - Docker
        - Electron
        - ESLint
        - Express.js
        - Feature
        - Flask
        - Go
        - GraphQL
        - HTML
        - Ionic
        - Jest
        - Java
        - JavaScript
        - Jenkins
        - JWT
        - Kubernetes
        - Laravel
        - Machine Learning
        - Maintenance
        - Markdown
        - Material-UI
        - Microservices
        - MongoDB
        - Mobile
        - Mockups
        - Mocha
        - Natural Language Processing
        - NestJS
        - Node.js
        - NUnit
        - OAuth
        - Performance Improvement
        - Prettier
        - Python
        - Question
        - React
        - React Native
        - Redux
        - RESTful APIs
        - Ruby
        - Ruby on Rails
        - Rust
        - Scala
        - Security
        - Selenium
        - SEO
        - Serverless
        - Solidity
        - Spring Boot
        - SQL
        - Swagger
        - Tailwind CSS
        - Test
        - Testing Library
        - Three.js
        - TypeScript
        - UI/UX/Design
        - Virtual Reality
        - Vue.js
        - WebSockets
        - Webpack
        - Other
    validations:
      required: true

  - type: dropdown
    id: ticket-mentorship
    attributes:
      label: Mentorship Status
      description: "Choose the mentorship status for this ticket"
      multiple: false
      options:
        - Mentor Required
        - Mentor Selected
        - Mentorship Completed
        - Mentor not required
    validations:
      required: true

  - type: textarea
    id: ticket-mentors
    attributes:
      label: Mentor(s)
      description: "Please tag relevant mentors for the ticket"
      placeholder: "Tag mentors using their GitHub handles (@username)"
    validations:
      required: true

  - type: dropdown
    id: ticket-complexity
    attributes:
      label: Complexity
      description: "Choose a complexity describing the complexity of your ticket"
      multiple: false
      options:
        - Foundational
        - Low
        - Medium
        - High
        - Advanced
    validations:
      required: true

  - type: dropdown
    id: ticket-project-type
    attributes:
      label: Contribution Type
      description: "Choose the labels that best describe this project"
      multiple: true
      options:
        - Code contribution
        - UI / UX design 
        - Advisory
        - Mentorship
        - Others
    validations:
      required: true

  - type: dropdown
    id: ticket-issue-type
    attributes:
      label: Issue Type
      description: "Choose the labels that best describe this ticket"
      multiple: true
      options:
        - Unpaid ticket
        - Paid ticket
        - Bounty ticket 
    validations:
      required: true

  - type: textarea
    id: ticket-monetary-incentive
    attributes:
      label: Monetary Incentive
      description: "Please mention the amount (in INR/USD) in case of a bounty / paid ticket. Please mention NA in case it is an unpaid ticket"
      placeholder: "Enter amount in INR/USD or NA"
    validations:
      required: true
