version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=beneficiary_user
      - DB_PASSWORD=your_secure_password
      - DB_NAME=beneficiary
      - DB_SSLMODE=disable
      - LOG_LEVEL=info
      - LOG_PRETTY_PRINT=true
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=beneficiary_user
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_DB=beneficiary
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 